name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  macosx:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          cache: npm
      - run: npm install
      - run: npm test
      - run: ./build.sh
      - uses: actions/upload-artifact@v1
        with:
          name: alfred-emoji-macosx.alfredworkflow
          path: alfred-emoji.alfredworkflow
  # macos11:
  #   runs-on: macos-11.0
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: actions/setup-node@v1
  #   - run: npm install
  #   - run: npm test
  #   - run: ./build.sh
  #   - uses: actions/upload-artifact@v1
  #     with:
  #       name: alfred-emoji-macos11.alfredworkflow
  #       path: alfred-emoji.alfredworkflow
